// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpcLib.generatedStubs;

public final class Service {
  private Service() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protolib_Number_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protolib_Number_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rService.proto\022\014com.protolib\"\025\n\006Number\022" +
      "\013\n\003num\030\001 \001(\0052E\n\010Addition\0229\n\tIncrement\022\024." +
      "com.protolib.Number\032\024.com.protolib.Numbe" +
      "r\"\000B\036\n\032com.grpcLib.generatedStubsP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_protolib_Number_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protolib_Number_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protolib_Number_descriptor,
        new java.lang.String[] { "Num", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
