// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service.proto

package com.grpcLib.generatedStubs;

public interface NumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protolib.Number)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 num = 1;</code>
   * @return The num.
   */
  int getNum();
}
